export default [
    {
      id: 1,
      nombre: "Escribanos de Nunca Jamás",
      empresa: "AEDOMEX, Asociación de Estudiantes del Estado de México",
      clave: "WA1058",
      crn: "922",
      grupo: "2588",
      duracion: "15 Semanas",
      horas: "120",
      tipo: "presencial",
      cupo: "20",
      objetivo: "Promover la autoconfianza, el autoconocimiento y el desarrollo de la creatividad en niños, niñas y adolescentes en situaciones de vulnerabilidad por medio del desarrollo de habilidades narrativas y argumentativas, buscando mejorar sus habilidades a lo largo de las 15 semanas de trabajo.",
    },
    {
      id: 2,
      nombre: "Capacitaciones Digitales y Tecnológicas",
      empresa: "Club de Niños y Niñas de Nuevo León, A.B.P.",
      clave: "WA1068",
      crn: "2767",
      grupo: "501",
      duracion: "10 Semanas",
      horas: "80",
      tipo: "presencial",
      cupo: "10",
      objetivo: "Brindar conocimiento en herramientas digitales y tecnológicas a la adolescencia, juventud y adultez de nuestro Club para un mejor desempeño académico y laboral, poniéndolo en práctica en sus entregables/proyectos escolares y exposiciones/clases laborales.",
    },
    {
      id: 3,
      nombre: "Inglés para todos en Conafe",
      empresa: "CONAFE, Consejo Nacional de Fomento Educativo",
      clave: "WA1067",
      crn: "415",
      grupo: "2756",
      duracion: "10 Semanas",
      horas: "80",
      tipo: "remoto",
      cupo: "25",
      objetivo: "Contribuir a la mejora del logro académico del idioma inglés como segunda lengua extranjera en los estudiantes de las escuelas comunitarias atendidas por el CONAFE en el estado de Nuevo León, mediante un programa de tutorías por pares para disminuir el impacto de las restricciones sanitarias derivadas del COVID-19 y buscar incrementar en un 10% el logro de los trayectos de aprendizaje en los estudiantes, a lo largo de 10 semanas.",
    },
  ];
  